Migrate to Eslint, uninstall tslint and fix some issues
AwesomeDocs/AwesomeDocs pull request #15
Opened 2020-10-06 02:45 UTC by yogmel

This fixes issue #13

2020-10-06 04:14 UTC, k3rn31p4nic requested changes
Apart from the suggestions I've made, why was the `tsconfig.json` file removed? It isn't related to TSLint. It's for configuring the TypeScript interpreter.

2020-10-06 04:14 UTC, iamtraction commented on .vscode/settings.json
> +{
You probably added this file by mistake. It should be removed.

2020-10-06 04:14 UTC, k3rn31p4nic commented on package.json
> +    "lint": "yarn eslint . --ext .js --ext .ts --fix"
This won't lint any of the files, use this instead:
```suggestion
    "lint": "./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx"
```

2020-10-06 04:14 UTC, k3rn31p4nic commented on .eslintignore
> +gatsby-node.js
These files should be linted too, instead of being ignored.

2020-10-06 04:14 UTC, k3rn31p4nic commented on .eslintrc.yml
> +  ecmaVersion: 2018
Bump ECMAScript version to 2020:
```suggestion
  ecmaVersion: 2020
```

2020-10-06 22:48 UTC, yogmel commented
@k3rn31p4nic sorry I have never implemented Eslint before. Hopefully it looks better now.

2020-10-07 01:48 UTC, k3rn31p4nic commented
No problem.

2020-10-07 01:48 UTC, k3rn31p4nic approved these changes

2020-10-07 01:49 UTC, merged